<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([[
            'name' => 'Armband met glitterrand',
            'description' => 'Description for Product 1',
            'image' => 'images/bracelets/armband_met_glitterrand.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Kleurenarmband',
            'description' => 'Description for Product 2',
            'image' => 'images/bracelets/kleurenarmband.jpg',
            'price' => 15.99,
            'stock' => 10,
            'on_sale' => true,
            'discount_factor' => 0.2, // 20% korting
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Laagjes armband met steentjes',
            'description' => 'Description for Product 3',
            'image' => 'images/bracelets/laagjes_armband_steentjes.jpg',
            'price' => 10.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Sierlijke armband',
            'description' => 'Description for Product 4',
            'image' => 'images/bracelets/sierlijke_armband_rotated.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Dubble twisted oorbellen dik',
            'description' => 'Description for Product 5',
            'image' => 'images/earrings/dubbel_twisted_oorbellen_dik.jpg',
            'price' => 22.99,
            'stock' => 10,
            'on_sale' => true,
            'discount_factor' => 0.2, // 20% korting
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Elegante oorbellen',
            'description' => 'Description for Product 6',
            'image' => 'images/earrings/elegante_oorbellen.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Enkel twisted oorbellen',
            'description' => 'Description for Product 7',
            'image' => 'images/earrings/enkel_twisted_oorbellen.jpg',
            'price' => 24.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Harten oorbellen',
            'description' => 'Description for Product 8',
            'image' => 'images/earrings/harten_oorbellen.jpg',
            'price' => 14.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Sierlijke oorbellen',
            'description' => 'Description for Product 9',
            'image' => 'images/earrings/sierlijke_oorbellen.jpg',
            'price' => 12.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Spiraal oorbellen met steen',
            'description' => 'Description for Product 10',
            'image' => 'images/earrings/spiraal_oorbellen_met_steen.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 4,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Bloemenketting',
            'description' => 'Description for Product 11',
            'image' => 'images/necklaces/bloemenketting.jpg',
            'price' => 22.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "Kleurenketting met kleurenarmband",
            'description' => "Description for Product 12",
            "image" => "images/necklaces/kleurenketting_met_kleurenarmband.jpg",
            "price" => 24.99,
            "stock" => 10,
            "on_sale" => false,
            "discount_factor" => null,
            "category_id" => 3,
            'created_at' => now(),
            'updated_at' => now(),
            
        ],
        [
            'name' => 'Laagjes ketting met roos',
            'description' => 'Description for Product 13',
            'image' => 'images/necklaces/laagjes_ketting_roos.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => true,
            'discount_factor' => 0.15, // 15% korting
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Sierlijke bloemenketting',
            'description' => 'Description for Product 14',
            'image' => 'images/necklaces/sierlijke_bloemenketting.jpg',
            'price' => 15.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Basic ring',
            'description' => 'Description for Product 15',
            'image' => 'images/rings/basic_ring.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Enkel twisted met dubbel twisted ring',
            'description' => 'Description for Product 16',
            'image' => 'images/rings/enkel_twisted_met_dubbel_twisted_ring.jpg',
            'price' => 24.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Hartjes ring',
            'description' => 'Description for Product 17',
            'image' => 'images/rings/hartjesring.jpg',
            'price' => 22.99,
            'stock' => 10,
            'on_sale' => false,
            'discount_factor' => null,
            'category_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Ring met twist',
            'description' => 'Description for Product 18',
            'image' => 'images/rings/ring_met_twist.jpg',
            'price' => 19.99,
            'stock' => 10,
            'on_sale' => true,
            'discount_factor' => 0.2, // 20% korting
            'category_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
    }
}
